name: Terraform Deployment

on:
  push:
    branches: [task_1]
  pull_request:
    branches: [task_1]

jobs:
  terraform_init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Create terraform cache
        uses: actions/cache/save@v4
        with:
          path: .terraform*
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}
          
  terraform_check:
    runs-on: ubuntu-latest
    needs: terraform_init
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore terraform cache
        uses: actions/cache/restore@v4
        with:
          path: .terraform*
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: true
          
      - name: Terraform Plan
        run: terraform fmt

  terraform_plan:
    runs-on: ubuntu-latest
    needs: terraform_check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore terraform cache
        uses: actions/cache/restore@v4
        with:
          path: .terraform*
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole

      - name: Terraform Plan
        run: terraform plan -input=false

  terraform_apply:
    runs-on: ubuntu-latest
    needs: terraform_plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore terraform cache
        uses: actions/cache/restore@v4
        with:
          path: .terraform*
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole

      - name: Terraform Apply
        run: terraform apply -auto-approve

